### ISSUE TITLE
Allauth forgot password

### ISSUE THREAD

**Issue by andrewfam** [SparkPost/python-sparkpost#102]
Using the django allauth package to do my auth.

Clicking the forget password and sending by email, I get below.
No idea how to debug. How do i event add stuff to the content.html?

sparkpost.exceptions.SparkPostAPIException
SparkPostAPIException: Call to https://api.sparkpost.com/api/v1/transmissions returned 422, errors:

        required field is missing: content.inline_images requires content.html

Using this works
EMAIL_HOST = 'smtp.sparkpostmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'SMTP_Injection'
EMAIL_HOST_PASSWORD = '348b25528c6b64abc0b423307314292c108d8899'
EMAIL_USE_TLS = True

**Comment by amatissart** [comment]
This is as bug in the last release, due to `inline_images` being set by default even if the messages does not contain html. See PR #99 
A workaround may be to define a html alternative in the message.
