### ISSUE TITLE
Support SparkPost in django-anymail

### ISSUE THREAD

**Issue by ojwoodford** [SparkPost/python-sparkpost#105]
This isn't an issue related directly to this repository, but it seemed like a good place to reach out to the developers at SparkPost on this issue.

With Mandrill now having no free tier, customers are looking to migrate to other ESPs. SparkPost seems like a good candidate, as it has a similar UI to Mandrill, has a generous free tier and a helpful migration tool. The latter is important, because businesses on the free tier probably don't want to spend a lot of time and money on switching.

It therefore makes sense that migrating the backend to SparkPost is easy too. [django-anymail](https://github.com/anymail/django-anymail) has made it easy to migrate from djrill, a package which supported only Mandrill, to its ESP-agnostic interface, making it easy to switch to any one of a number of supported ESPs. However, SparkPost is not currently supported.

This is a shame. With support for SparkPost in django-anymail, it would make it easier still for django users to migrate from Mandrill to SparkPost.

I've made [a request for its support on that repository](https://github.com/anymail/django-anymail/issues/11), but I also thought it would be worth raising it with you here.

**Comment by ojwoodford** [comment]
SparkPost almost but [not quite working](https://github.com/anymail/django-anymail/issues/24) with django-anymail.

**Comment by richleland** [comment]
Looks like this is in django-anymail - thank you! In version 2.0 of this library I'd like to consider the idea of pushing folks to use anymail instead of including the Django backend.
