### ISSUE TITLE
Django backend -unable to use templates and substitution_data

### ISSUE THREAD

**Issue by J0hnyBrav0** [SparkPost/python-sparkpost#107]
While using `EMAIL_BACKEND = 'sparkpost.django.email_backend.SparkPostEmailBackend'` and creating a message like this:
 ```
 msg = EmailMultiAlternatives(
    to=to_list
  )
  msg.template = template
  msg.substitution_data = substitution_data
```
I've encountered several problem with missing params. After debugging I've found out that template and substitution_data are ignored. becasue they are not considered as a part of SparkPostMessage class. As result `_send(self, message)` in `SparkPostEmailBackend` is also ignoring those params.

If it's not a bug, then please provide an explanation in documentation how to use `SparkPostEmailBackend` and send emails using substitution data and templates.

**Comment by richleland** [comment]
Hi @J0hnyBrav0 thanks for reporting this. It's an issue for sure - looking into the best way to support other attributes. We basically just covered what would come across in the standard Django API, but extending it to allow other attributes makes a lot of sense.

**Comment by richleland** [comment]
Well nevermind - page didn't refresh - I saw your PR - checking it out now!
