### ISSUE TITLE
Django backend raises KeyError Exception when the API returns an error

### ISSUE THREAD

**Issue by pegler** [SparkPost/python-sparkpost#120]
Today the API was returning the error `{u'errors': [{u'message': u'Unable to contact authorization service.'}]}` which causes the Django backend to raise an error because the key total_accepted_recipients was not in the response.  The Django backend should handle API errors more robustly

**Comment by richleland** [comment]
@pegler I know this ticket is old, but wondering if you're still seeing this. The exception handling of the underlying `Transmission.send` method has been improved and I think this is now a non-issue. Let me know if that's not the case, and thanks for reporting.

**Comment by pegler** [comment]
we've been using a fork for a while so I haven't checked if the official lib is working as expected.  I'll try to take a look and let you know

**Comment by richleland** [comment]
That's cool thanks @pegler. Curious - would you be willing to switch back to the official lib? Also if there is anything you've done in your fork we would ❤️  to see it and possibly pull it in.
