### ISSUE TITLE
Investigate using library on Google App Engine

### ISSUE THREAD

**Issue by richleland** [SparkPost/python-sparkpost#126]
As reported by `@timcederman` in our #python channel in community Slack, the library does not appear to work with Google App Engine:

> has anyone succeeded in getting the Python SDK to work for Google App Engine? I'm hitting issues because of the requests library, which seems to be incompatible with using GAE.
> 
> huh, I finally resolved this by downgrading to requests 2.1.0, but now the exception handling in the sparkpost sdk is broken

**Comment by richleland** [comment]
After investigation, there is a way to monkey patch Google Cloud to allow the use of the requests library. I've documented this in the [README](https://github.com/SparkPost/python-sparkpost#using-with-google-cloud).

**Comment by NilsRG** [comment]
Could this error be related?

SparkPostAPIException: Call to https://api.sparkpost.com/api/v1/transmissions returned 422, errors: Invalid header Code: 3002 Description: Error while validating header From: Header content all whitespace

**Comment by richleland** [comment]
Hi @NilsRG that appears unrelated. For some reason the From header is empty when the underlying call is made to the API. Could you share a snippet of the code you are using so we can troubleshoot? If you could put that in another issue that would be great - thanks!

**Comment by NilsRG** [comment]
I "solved" it by hard-coding as many of the parameters as I could. Unfortunately I don't have time to figure out what I did wrong originally... Do you want me to delete these comments, as they probably are unrelated?

**Comment by richleland** [comment]
No that's OK - I'm going to go ahead and close - but feel free to open a new issue if you run into anything related to your issue again.
