### ISSUE TITLE
TypeError when sending to an umlaut domain

### ISSUE THREAD

**Issue by chschuermann** [SparkPost/python-sparkpost#134]
One of our older Python 2.7 projects ran into an error when sending a transactional email to a domain containing an umlaut (e.g. "someone@my-umlaut-domäin.com"). Our transmission includes recipient attributes:

```
sp.transmissions.send(
    recipients=[{
        'address': {
            'name': u'Firstname Lastname',
            'email': u'someone@my-umlaut-domäin.com',
        }
    }],
    template='my-template'
)
```

The package version 1.1.1 gave us the following error:
`At least one valid recipient is required`

Updating to the latest release 1.3.2 returned this error:
`TypeError: sequence item 0: expected string, dict found`

Unicode recipients should be supported since package version 1.0.3. Is there something we miss?

**Comment by alexrada** [comment]
I'm getting the same error with an unicode email address.

> sparkpost/exceptions.py\", line 30, in __init__\n    errors='\\n'.join(errors)\nTypeError: sequence item 0: expected string, dict found\n", "err_details": "TypeError('sequence item 0: expected string, dict found',)"

**Comment by richleland** [comment]
Hi @chschuermann @alexrada taking a look at this - sorry for the crazy delay! I'll follow up with findings.

**Comment by richleland** [comment]
Update - did some debugging - there are two issues here - the unicode chars not working in from email addresses, and the improper handling of the error messages. The error issue should be easy to fix up, and I'll continue to investigate the unicode problem.

**Comment by richleland** [comment]
OK, I've got some info for you @chschuermann @alexrada. Support for [SMTPUTF8](https://tools.ietf.org/html/rfc6531) is very thin - most receiving MTAs do not accept recipient emails with domains with UTF8 characters. We run stats to check for support periodically and our most recent check showed about 1% support. That said, you can punycode encode the domain before submitting to SparkPost, which will be accepted and sent properly.

Following is an example of how you'd pull this off given the domain above:

```python
```

**Comment by richleland** [comment]
I'm going to go ahead and close this out, but feel free to report any further issues related to this.
