### ISSUE TITLE
reply-to

### ISSUE THREAD

**Issue by sandroden** [SparkPost/python-sparkpost#148]
Hi,

I'm using python-sparkpost since a while, but I realized that I can't make reply-to work correctly. It does work if I write it in the template definition (on the website), it does not work if I pass it as argument in the transmission. 

Looking at the code it seems that python-sparkpost correctly puts it in the content array. I'm using it with a template-name referring a template stored on sparkpost.

Any help is appreciated. Thanks in advance
sandro
*:-)

**Comment by richleland** [comment]
Hi @sandroden can you post a code snippet for debugging purposes? Thanks!

**Comment by wodow** [comment]
I believe that field isn't supported for "stored templates" - see the caveat at https://developer.sparkpost.com/api/transmissions.html#header-inline-content-attributes

**Comment by jgzamora** [comment]
If you are using a template, set the `reply-to` attribute in the template's `content` object. This can also be easily done from the [app](https://app.sparkpost.com/templates)
