### ISSUE TITLE
Add support for events management

### ISSUE THREAD

**Issue by cisarpavel** [SparkPost/python-sparkpost#149]
Message events are huge part of sparkpost system and api with meny types of events, but this lib missing them totaly. Listing events, searching events ...

Thanks

Pavel Cisar

**Comment by richleland** [comment]
Hi @cisarpavel you can use the underlying base resource to create your own subclass for any items we haven't created a class for. Check out [this example](https://github.com/SparkPost/python-sparkpost/blob/master/examples/base_resource.py) using webhooks.

Also worth noting is that we're working on 2.x, which will have a much simpler [base resource](https://github.com/SparkPost/python-sparkpost/issues/145). As such we won't be adding a Message Events specific resource to 1.x

Hope this helps! I'm going to go ahead and close out this issue, but let us know if you have any questions about implementing your own custom class in 1.x.
