### ISSUE TITLE
Attachment Support

### ISSUE THREAD

**Issue by jpatel3** [SparkPost/python-sparkpost#157]
Is there attachment support in this API? I see in the [documentation](https://www.sparkpost.com/docs/user-guide/sending-attachments/), it does say that it supports attachment with the inline template, so I am assuming it might be available, but couldn't locate the documentation readme.

**Comment by ewandennis** [comment]
Yup, there's a python [example of sending a transmission with an attachment here](https://python-sparkpost.readthedocs.io/en/latest/resources/transmissions.html#sending-an-attachment).

The [API reference for transmissions is here](https://developers.sparkpost.com/api/transmissions.html) and the [section about attachments is here](https://developers.sparkpost.com/api/transmissions.html#header-attachment-attributes).
