### ISSUE TITLE
How do I send a Django email with a custom From header?

### ISSUE THREAD

**Issue by YPCrumble** [SparkPost/python-sparkpost#161]
I'm attempting to set a different MAIL_FROM and `From` header in Django so that I can use a custom bounce domain. Django allows this [by setting the bounce domain as the email's `self.from_email` attribute, and overriding the `From` header manually](https://code.djangoproject.com/ticket/9214#no1).

However, this yields the Sparkpost API error pasted below. I'm using Django Anymail 1.3 with python-sparkpost 1.3.5. Any suggestions would be tremendous!

```
Sending a message to test@example.com from mail@bounces.example.com
SparkPost API response 422: Unprocessable Entity
{
  "errors": [
    {
      "message": "Invalid header",
      "description": "Error while validating header From: 'From' header must be specified in content.from.name and content.from.email",
      "code": "3002"
    }
  ]
}
```

**Comment by YPCrumble** [comment]
Update - it looks like [the way this library constructs the `from_email`](https://github.com/SparkPost/python-sparkpost/blob/f3d2ec6dac0be7c84dd5774e446aa7a51693b68d/sparkpost/transmissions.py#L53) differs from [how Django constructs the `from_email` attribute](https://github.com/django/django/blob/a38ae914d89809aed6d79337b74a8b31b6d3849a/django/core/mail/message.py#L256). Django first looks for `From` in its `extra_headers` attribute, while this library takes the `from_email` without allowing the override. 

I'd be happy to submit a PR if that's helpful. I could also potentially understand suggesting that I add a custom `return_path` to Anymail's `esp_extra` dictionary, which I believe would adjust the currently undocumented `return_path` parameter on the `transmissions.send` method. Happy to add a PR to document `return_path` here if that's helpful instead: https://github.com/SparkPost/python-sparkpost/blob/f3d2ec6dac0be7c84dd5774e446aa7a51693b68d/sparkpost/transmissions.py#L34

**Comment by jgzamora** [comment]
@YPCrumble awesome work digging up all the parts of this issue! I will document `return_path` for this lib and check if there are any other params that need documenting. It looks like your use case is currently possible, so I'm going close this issue. If you still still think we should update to better match how Django does this, please create another issue so we can discuss it in more detail.
