### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by fahzee1** [SparkPost/python-sparkpost#167]
Trying to install this in my virtualenv and it doesn’t work. Do you guys have another version by another name or something?

Downloading/unpacking sparkpost
  Could not fetch URL https://pypi.python.org/simple/sparkpost/: There was a problem confirming the ssl certificate: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
  Will skip URL https://pypi.python.org/simple/sparkpost/ when looking for download links for sparkpost
  Could not fetch URL https://pypi.python.org/simple/: There was a problem confirming the ssl certificate: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
  Will skip URL https://pypi.python.org/simple/ when looking for download links for sparkpost
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/sparkpost/: There was a problem confirming the ssl certificate: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
  Will skip URL https://pypi.python.org/simple/sparkpost/ when looking for download links for sparkpost
  Could not find any downloads that satisfy the requirement sparkpost
Cleaning up...
No distributions at all found for sparkpost

**Comment by jgzamora** [comment]
Hey @fahzee1, thanks for reporting. Would you mind adding the version of Python and OS you are using? I've seen similar issues to this one relating to OpenSSL

**Comment by fahzee1** [comment]
Python 2.7 and mac os 10.12.

**Comment by jgzamora** [comment]
@fahzee1 Your issue looks really close to this one:

https://github.com/pypa/pip/issues/5236

Mind going through the steps outlined there to see if it solved your problem? 

I found a couple other issues that were similar regarding SSL + pip:
https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version
https://github.com/pypa/python-packaging-user-guide/issues/423

**Comment by fahzee1** [comment]
`curl https://bootstrap.pypa.io/get-pip.py | python` fixed the issue. Thanks @jgzamora

**Comment by jgzamora** [comment]
Awesome!
