### ISSUE TITLE
Engagment Tracking always get set on transmission

### ISSUE THREAD

**Issue by bizob2828** [SparkPost/python-sparkpost#17]
Engagement tracking flags always get set on transmissions no matter if they are sent or not. This prevents the ability to fall back to the settings set on a saved template for these values.

**Comment by richleland** [comment]
Looks like @bizob2828 did all the work here - it's just buried in PR #18. We also shoved some other stuff in that PR like wheel support. We should just cherry pick out relevant commits.

**Comment by aydrian** [comment]
What needs to be cherry picked? I see some commits in there for things that already exist in master.

**Comment by richleland** [comment]
Yeah... um... I think it's probably just worth creating a new branch and pulling over specifics. I can do that since I have a feel for what actually does need to be pulled in.

**Comment by richleland** [comment]
Submitted #43.
