### ISSUE TITLE
from_email long format doesn't seem to handle commas in name (unless name is quoted)

### ISSUE THREAD

**Issue by abathur** [SparkPost/python-sparkpost#177]
This isn't actually your bug, but I thought you might want to document it, or perhaps support an optional explicit `{"name": x, "address": y}` format.

I attempted to specify a `from_email` along the lines of `'Company Name, LLC <address@example.com>'` and got error messages like:

    sparkpost.exceptions.SparkPostAPIException: Call to https://api.sparkpost.com/api/v1/transmissions returned 400, errors:
    Invalid domain Code: 7001 Description: No sending domain specified 

I tracked this down to the `parseaddr` function in Python's `email.utils` module, which is behaving like:

    >>> from email.utils import parseaddr
    >>> parseaddr("Company Name, LLC <address@example.com>")
    ('', 'Company')
    >>> parseaddr("Company Name LLC <address@example.com>")
    ('Company Name LLC', 'address@example.com')

**Updated**: It looks like quoting the name portion can fix this, so it might be sufficient to suggest as much in the documentation. Example:

    >>> parseaddr('"Company Name, LLC" <address@example.com>')
    ('Company Name, LLC', 'address@example.com')

**Comment by jgzamora** [comment]
Hey @abathur, thanks for reporting. It looks like it's generally working as expected but could use some extra documentation around formatting recipients. Also wanted to let you know that the lib already does support `{"name": x, "address": y}` recipients:
```
:param list|dict recipients: List of email addresses, or a dict:
            ``{'address': {'name': 'Kyla', 'email': 'hello@example.com' }}``
```
https://python-sparkpost.readthedocs.io/en/latest/api/transmissions.html#sparkpost.transmissions.Transmissions.send

I think we may also be able to add some helpful parsing & errors to the lib itself to avoid passing obviously wrong info to the API.
