### ISSUE TITLE
Support for EU accounts in the Django backend.

### ISSUE THREAD

**Issue by jkeyes** [SparkPost/python-sparkpost#187]
There is currently no way to configure the Django backend to use the EU API.

**Comment by medmunds** [comment]
FYI, the SparkPost EmailBackend in the [django-anymail](https://anymail.readthedocs.io) package has had the ability to use SparkPost's EU, labs, and enterprise API endpoints since [v2.1](https://anymail.readthedocs.io/en/stable/changelog/#v2-1) (2018-04-11). [Full disclosure: I maintain Anymail.]

**Comment by nickperkins** [comment]
This was resolved by #188
