### ISSUE TITLE
Unable to install Pre-Release version of SDK

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/python-sparkpost#19]
Using pip > 1.4.x there is no longer support for pre-release packages (like the SparkPost Python SDK) unless you use the --pre option on the pip command.

Adding this issue from this question on Stackoverflow:
http://stackoverflow.com/questions/29871778/sparkpost-python-sdk-install-failing/29871893

Here's the reference I found that helped me resolve this issue:
http://stackoverflow.com/questions/18230956/could-not-find-a-version-that-satisfies-the-requirement-pytz

**Comment by richleland** [comment]
So I think this is a good thing - we just need to add to the README that you have to use the --pre flag. Alternatively, we'd have to release a version without the `dev1` suffix.

**Comment by richleland** [comment]
I'm thinking we need to change the version here. Since we've never released a non-pre-release version, we could change it to ``0.1.0``, push to PyPI as-is, and then continue development as ``0.2.0dev1`` until we have ``0.2.0`` ready. Thoughts?

**Comment by aydrian** [comment]
I'm okay with that, but doesn't 0.x.x already signify a prelease? How would that work going forward? We would do dev revisions on 0.2.0 until we are ready to release non-pre-release 0.2.0?

**Comment by richleland** [comment]
Yeah that's a good point. I guess the ``devX`` stuff is really only necessary after 1.0.0. Let's just ditch the pre-release flags for anything pre-1.0.0.

**Comment by richleland** [comment]
pip has come a long way since this ticket opened. They are on 7.1.2 and this restriction doesn't exist. Closing.

**Comment by richleland** [comment]
Just wanted to add a note as to the reason this now works. As of pip 6.0 they fully support PEP 440 which handles installation of pre-release versions without the --pre flag. https://pip.pypa.io/en/latest/news.html
