### ISSUE TITLE
Unable to set all supported options on transmissions API

### ISSUE THREAD

**Issue by michielvv** [SparkPost/python-sparkpost#191]
The options the API allows are not consistent with what the library supports.

e.g.  the API offers   perform_substitutions  as an option, but there is no way to set this in the python call.  (in general the fact that naming and structure is different from the API is somewhat confusing)

Maybe give the option to initialize options yourself in`Transmissions._translate_keys` :
`'options': kwargs.get('options', {})`  
?

**Comment by duanehutchins** [comment]
Check out my PR #193. It looks like it will also fix your issue.
