### ISSUE TITLE
POST to /transmissions using a Campaign ID

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/python-sparkpost#21]
The REST API Documentation has "campaign_id" listed as the property to use in all the human readable documentation.

Shouldn't the SparkPost Python SDK POST to /transmission use the same property name instead of "campaign" as you can see here:

https://github.com/SparkPost/python-sparkpost/blob/master/examples/transmissions/send_transmission.py#L26

**Comment by aydrian** [comment]
@richleland: Thoughts? There is no central place for creating campaigns and there is no title, just an id. Should the property be campaign_id just to express format? Is there a format limitation? Does it have to be "my_campaign" or can it be "My Campaign"?

**Comment by richleland** [comment]
So I'm not sold on changing this - we abstract away some of the names of the properties - template_id is template, list_id is recipient_list, campaign_id is campaign. To me it's more human than the API fields. The format of this field is pretty open ended.

**Comment by aydrian** [comment]
I agree and am fine with this.
