### ISSUE TITLE
Map POST/PUT Payloads to the API documentation

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/python-sparkpost#22]
It is confusing for developers to use a flattened structure of their request payloads, especially when the property names vary from the API documentation on SparkPost.com/api.

Use a idiomatic structure passthrough that maps to the API docs for all first class citizens of the SparkPost API.

**Comment by aydrian** [comment]
This is not so confusing to a python developer. The code is well documented and the developer shouldn't have to look past that to an API doc. Let's use the python language to add simplicity which is what we ultimately want.
