### ISSUE TITLE
Create wrapper for webhooks API

### ISSUE THREAD

**Issue by aydrian** [SparkPost/python-sparkpost#24]
https://www.sparkpost.com/api#/reference/webhooks

**Comment by bizob2828** [comment]
I recommend we not do this.  Webhooks API is rarely used and I see little value of having this in a SDK

**Comment by techdragon** [comment]
Given that receiving unsubscribe actions seem to be driven by the webhooks API, unless there is an alternative then handling at least some webhooks such as 'unsubscribe' events seems extremely worthwhile. Especially now that many users are coming from systems like Mandrill where the unsubscribe links were taken care of much more automatically than they are with SparkPost.

**Comment by richleland** [comment]
Hi @techdragon this wrapper wouldn't be a webhook consumer, it would just be a wrapper around retrieving, creating, updating, and deleting the webhooks themselves. Writing a webhook consumer is a very customer-specific task (each person/company has their own use cases), so trying to write one within the library that is generic enough for all needs would be near impossible.

**Comment by techdragon** [comment]
Hi @richleland Sorry for mistaking this for webhook consumer and while I concur in general, I feel there are some specific cases where it would be simple and advantageous to build a 'sparkpost webhook consumer' that would be useful for the majority of users using it. For Django a generic 'webhook receiver' library/module would be able to handle the boilerplate of receiving and validating the incoming webhooks,  while being able to have easily customised URLs using Django's URL functionality, and could simply 'hand off responsibility' to customer specific code by offering a custom signal they can react to. I've seen this pattern used in the past for service specific webhooks and it can be quite useful.

**Comment by richleland** [comment]
Going to close this out based on original ticket purpose. Thanks for your thoughts on a generic webhook consumer @techdragon - definitely helpful to understand the use case. Can't promise anything but will take this feedback into account if we end up building a consumer example in Django.
