### ISSUE TITLE
make test returning errors

### ISSUE THREAD

**Issue by aydrian** [SparkPost/python-sparkpost#27]
When you run `make test` it doesn't make it past the flake8 validation. If you bypass that and run `venv/bin/activate; py.test --cov sparkpost test/`, import errors are returned. We must get tests running and passing before moving forward.

**Comment by richleland** [comment]
I can help with this @aydrian - the problem is in TravisCI we're just running tox whereas with `make test` we're running py.test directly and flake8. We just need to align with tox and add flake8 as an env to tox.

**Comment by aydrian** [comment]
Thank you. We need to include something on a contribute page so everyone knows how to run them before submitting a pull request.
