### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by yepher** [SparkPost/python-sparkpost#51]
Caveat to this issue: I maybe misreading the code and there is another way to do this that I am not seeing.

While working on the Java SDK I see this project and PHP SDK require the API Key to be set inside a checked in file. [Example](https://github.com/SparkPost/python-sparkpost/blob/master/examples/transmissions/send_transmission.py#L3)

I believe things like that should not be placed inside checked in code because it is too easy to accidentally checkin you key.

I would prefer to see a name something like "config.something.example" that gets checked in. Put "config.something" would be put in the .gitignore so ti is not checked in. The example file would have the place holder properties.

The above filenames should use something appropriate for the language. In Java it would probably be "config.properties.example".

**Comment by bizob2828** [comment]
ideally we can update the example.  The way we see this is you put your key in an env var and reference as `os.environ['SPARKPOST_API_KEY']`

**Comment by yepher** [comment]
That seems like a very reasonable solution. The probably I have run into with that method is when you want to have multiple branches or project that point at different accounts or clusters. (like on a build server).

But I think that solution is much better than putting directly into the code.

**Comment by richleland** [comment]
I say we just remove the ``YOUR_API_KEY`` from the examples. We already document how this works using an env var here: https://github.com/SparkPost/python-sparkpost#get-a-key
