### ISSUE TITLE
Support email attachments

### ISSUE THREAD

**Issue by rajumsys** [SparkPost/python-sparkpost#56]
Sending attachment isn't supported at this moment. We need to add that support for attachment in python (including in Django backend).

**Comment by richleland** [comment]
The API now support this, though the customer must contact support@sparkpost.com to enable. We'll want to make note of this once we implement.

**Comment by donspaulding** [comment]
Any update on this?

**Comment by richleland** [comment]
Hi @donspaulding our API isn't restricted any longer so everyone can send attachments, but we still have to do this work in the library. I'm going to take some time here to get this working. Are there any of the other open issues that are particularly important to you? Anything you don't see that you'd like to see in the library?

**Comment by donspaulding** [comment]
Hi @richleland,
Thanks for the quick attention to this.  I'm a Mandrill refugee.  The other obvious issue I've seen is the lack of CC/BCC support via this library.  I think that would smooth out the transition for us.

Thanks,
Don

**Comment by richleland** [comment]
Awesome thanks for the extra details @donspaulding - we've got that identified in https://github.com/SparkPost/python-sparkpost/issues/55 if you'd like to follow along. This feedback helps and I'll let you know once we've made some progress on that front.
