### ISSUE TITLE
Schedule transmission

### ISSUE THREAD

**Issue by frepond** [SparkPost/python-sparkpost#58]
I don't see any option in the transmission api to schedule a transmission. I'm missing something?

**Comment by frepond** [comment]
Looking at the source code there's no option for scheduling... Is it going to be included anytime soon? I would prefer to stick to the official API rather than forking it. Regards.
  
```python
        model['options']['open_tracking'] = kwargs.get('track_opens')
        model['options']['click_tracking'] = kwargs.get('track_clicks')
        model['options']['sandbox'] = kwargs.get('use_sandbox')
```

**Comment by aydrian** [comment]
It shouldn't take us too long. I have added this to our next release. We'll update you when we have a better timeline.

**Comment by richleland** [comment]
@frepond this is up on PyPI as 1.0.0

**Comment by frepond** [comment]
Thanks!
