### ISSUE TITLE
Critical Error on Django Backend

### ISSUE THREAD

**Issue by gnarvaja** [SparkPost/python-sparkpost#88]
I've been two days behind a bug in the Django Backend. 

Some of the text-only emails were arriving in HTML and with the content of other totally different email. Only viewing the email in raw you can see the correct text content.

The problem was the backend was modifing the global settings dict.

#87 should fix this bug.

**Comment by richleland** [comment]
Published this to PyPI as 1.0.5. Thanks again for the PR.
