### ISSUE TITLE
Automatically parse long form emails in from field

### ISSUE THREAD

**Issue by richleland** [SparkPost/python-sparkpost#93]
When we have an email in the format `Example Person <person@example.com` supplied in the `from_email` we should automatically parse it into the longer form dict `from: { name: 'Example Person', email: 'person@example.com`` format. This gets around some issues related to unicode and how our system parses the long form.

**Comment by pegler** [comment]
I fixed this in my fork, which is included in https://github.com/SparkPost/python-sparkpost/pull/91

**Comment by richleland** [comment]
Fixed in #91
